/**
 * 💦 THIS IS AN AUTOGENERATED FILE. DO NOT EDIT DIRECTLY 💦
 *
 *    This file is generated on each build.
 *    It reflects basic meta-data about the module and it's dependencies
 *    Use it via a standard `import` statement
 *
 *    - DO NOT manually edit.
 *    - DO commit to source-control.
 */

export const Pkg: ModuleDef = {
  name: 'sys.util',
  version: '0.0.0',
  dependencies: {
    '@noble/hashes': '1.5.0',
    '@paralleldrive/cuid2': '2.2.2',
    'fast-json-patch': '3.1.1',
    'minimist': '1.2.8',
    'pretty-bytes': '6.1.1',
  },
  toString() {
    return `${Pkg.name}@${Pkg.version}`;
  },
};

export type ModuleDef = {
  name: string;
  version: string;
  dependencies: { [key: string]: string };
  toString(): string;
};
