/**
 * 💦 THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY 💦
 *
 *    This file is generated on each build.
 *    It reflects basic meta-data about the module and it's dependencies
 *    Use it via a standard `import` statement
 *
 *    - DO NOT manually edit.
 *    - DO commit to source-control.
 */

export const Pkg: ModuleDef = {
  name: 'sys.data.markdown',
  version: '0.0.0',
  dependencies: {
    'sys.types': '0.0.0',
    'sys.util': '0.0.0',
    'sys.util.css': '0.0.0',
    'sys.util.react': '0.0.0',
    'sanitize-html': '2.7.1',
    'rehype-format': '4.0.1',
    'rehype-stringify': '9.0.3',
    'remark-parse': '10.0.1',
    'remark-rehype': '10.1.0',
    'unified': '10.1.2',
    'react': '18.2.0',
  },
  toString() {
    return `💦 module: ${Pkg.name} (v${Pkg.version})`;
  },
};

export type ModuleDef = {
  name: string;
  version: string;
  dependencies: { [key: string]: string };
  toString(): string;
};
