/**
 * 💦 THIS IS AN AUTOGENERATED FILE. DO NOT EDIT DIRECTLY 💦
 *
 *    This file is generated on each build.
 *    It reflects basic meta-data about the module and it's dependencies
 *    Use it via a standard `import` statement
 *
 *    - DO NOT manually edit.
 *    - DO commit to source-control.
 */

export const Pkg: ModuleDef = {
  name: 'ext.lib.automerge.webrtc',
  version: '0.0.0',
  dependencies: {
    '@automerge/automerge': '2.2.8',
    '@automerge/automerge-repo': '1.2.1',
    '@automerge/automerge-repo-network-broadcastchannel': '1.2.1',
    '@automerge/automerge-repo-storage-indexeddb': '1.2.1',
    'automerge-repo-network-peerjs': '1.2.2',
    'ext.lib.automerge': '0.0.0',
    'ext.lib.peerjs': '0.0.0',
    'react': '18.3.1',
    'react-dom': '18.3.1',
    'sys.data.indexeddb': '0.0.0',
    'sys.util': '0.0.0',
    'sys.ui.react.common': '0.0.0',
  },
  toString() {
    return `${Pkg.name}@${Pkg.version}`;
  },
};

export type ModuleDef = {
  name: string;
  version: string;
  dependencies: { [key: string]: string };
  toString(): string;
};
