import { patch } from '@onsetsoftware/automerge-patcher';
import { type t, Is } from './common';

type O = Record<string, unknown>;

/**
 * Helpers to apply and invert patches generated by Automerge document changes.
 * See:
 *    https://github.com/onsetsoftware/automerge-patcher
 */
export const DocPatch = {
  /**
   * Apply one or more patches to a document.
   */
  apply<T extends O>(doc: T | t.Doc<T>, changeset: t.Patch | t.Patch[]): T {
    if (Is.doc(doc)) {
      doc.change((d) => DocPatch.apply(d, changeset));
      return doc.current;
    } else {
      const items = Array.isArray(changeset) ? changeset : [changeset];
      items.forEach((change) => patch<T>(doc, change));
      return doc;
    }
  },
} as const;
